version: '2.2'

services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
    container_name: es
    environment:
        - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_db:/usr/share/elasticsearch/data
    ports:
      - 127.0.0.1:9200:9200

  sql:
    image: mysql
    container_name: mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - mysql_db:/var/lib/mysql
    ports:
      - 127.0.0.1:3306:3306

volumes:
  es_db:
    driver: local
  mysql_db:
    driver: local
